name: E2E on Chrome

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v3
        continue-on-error: true
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          PASSWORD: ${{ secrets.PASSWORD }}
      
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: deploy
          path: backup
  
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: backup
          allure_history: allure-history
          allure_results: allure-results
  
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: deploy
          publish_dir: allure-history
          clean: true
